"""
Qdrant Vector Database Client.

Handles indexing and semantic searching of code snippets using
the embeddings generated by the contrastive GraphCodeBERT model.
"""
from __future__ import annotations

import uuid
from typing import Any, List
from loguru import logger

try:
    from qdrant_client import QdrantClient as Qdrant
    from qdrant_client.http import models
except ImportError:
    Qdrant = None
    models = None


class CodeVectorStore:
    def __init__(self, host: str = "localhost", port: int = 6333, collection_name: str = "secureai_code"):
        self.collection_name = collection_name
        self.client = None
        
        if Qdrant:
            try:
                self.client = Qdrant(host=host, port=port)
                self._ensure_collection()
            except Exception as e:
                logger.warning(f"Could not connect to Qdrant: {e}")

    def _ensure_collection(self) -> None:
        """Create the collection if it does not exist."""
        if not self.client:
            return
            
        collections = self.client.get_collections().collections
        if not any(c.name == self.collection_name for c in collections):
            logger.info(f"Creating Qdrant collection: {self.collection_name}")
            self.client.create_collection(
                collection_name=self.collection_name,
                vectors_config=models.VectorParams(
                    size=768,  # GraphCodeBERT embedding size
                    distance=models.Distance.COSINE
                ),
            )

    def index_snippets(self, embeddings: List[List[float]], payloads: List[dict[str, Any]]) -> None:
        """
        Index a batch of code snippets with their embeddings.
        Payloads should include: file_path, function_name, code_text.
        """
        if not self.client:
            logger.error("Qdrant client not initialized")
            return
            
        points = []
        for i, (emb, payload) in enumerate(zip(embeddings, payloads)):
            point_id = str(uuid.uuid4())
            points.append(
                models.PointStruct(
                    id=point_id,
                    vector=emb,
                    payload=payload
                )
            )
            
        # Upsert in batches of 100 for efficiency
        batch_size = 100
        for i in range(0, len(points), batch_size):
            batch = points[i:i + batch_size]
            self.client.upsert(
                collection_name=self.collection_name,
                points=batch
            )
            
        logger.info(f"Indexed {len(points)} snippets into Qdrant")

    def search(self, query_embedding: List[float], top_k: int = 10, filter_dict: dict = None) -> List[dict[str, Any]]:
        """
        Search for semantically similar code snippets.
        """
        if not self.client:
            logger.error("Qdrant client not initialized")
            return []
            
        qdrant_filter = None
        if filter_dict:
            # Simple keyword filtering for demonstration
            conditions = []
            for key, val in filter_dict.items():
                conditions.append(
                    models.FieldCondition(
                        key=key,
                        match=models.MatchValue(value=val)
                    )
                )
            if conditions:
                qdrant_filter = models.Filter(must=conditions)

        hits = self.client.search(
            collection_name=self.collection_name,
            query_vector=query_embedding,
            query_filter=qdrant_filter,
            limit=top_k
        )
        
        results = []
        for hit in hits:
            res = hit.payload.copy()
            res["score"] = hit.score
            results.append(res)
            
        return results
